import { ILabel } from '~bioblocks-viz~/data';

// tslint:disable-next-line: no-unnecessary-class
export class Marker {
  public static colors = {
    /**
     * Get ILabels with colors auto set based on a the states passed
     * into the function. The function can at most generate 20 unique
     * colors. If more states exist than the colorset, the states that occur
     * the most number of times will receive ILabels and the others
     * will get undefined.
     *
     *
     * @param states the set of states to auto generate colors for
     * @param [colorSet=Marker.colorSets.colorBrewer] an array of colors
     * @returns each element in the array will correspond to
     *          each state. There will be a single ILabel object
     *          for each unique state name (likely occurring multiple
     *          times in the array)
     */
    autoColorFromStates(
      states: Array<string | undefined>,
      colorSet: string[] = Marker.colorSets.colorBrewer,
    ): Array<ILabel | undefined> {
      const stateCounts = states.reduce<{ [state: string]: number }>((acc, state) => {
        if (state) {
          if (!acc[state]) {
            acc[state] = 0;
          }
          acc[state] += 1;
        }

        return acc;
      }, {});

      const sortedStateCountTuple = Object.entries(stateCounts).sort((a, b) => {
        if (a[1] === b[1]) {
          return 0;
        }

        return a[1] > b[1] ? -1 : 1;
      });

      const stateToColor = sortedStateCountTuple.reduce<{ [state: string]: ILabel | undefined }>(
        (acc, stateCountTuple, idx) => {
          acc[stateCountTuple[0]] = {
            color: idx < colorSet.length ? colorSet[idx] : '',
            name: stateCountTuple[0],
          };

          return acc;
        },
        {},
      );

      return states.map(state => {
        if (!state) {
          return undefined;
        }

        return stateToColor[state];
      });
    },
  };

  private static colorSets = {
    categorical: [
      // generated by http://vrl.cs.brown.edu/color
      '#069668',
      '#75e7dd',
      '#145a6a',
      '#c5d5f0',
      '#82269b',
      '#5361c7',
      '#e8a2de',
      '#479abc',
      '#11e38c',
      '#0b5313',
      '#bbcf7a',
      '#6e390d',
      '#f4d403',
      '#ae301f',
      '#34f50e',
      '#7c8a4f',
      '#f6bb86',
      '#b5753e',
      '#fe1d66',
      '#9bea30',
    ],
    colorBrewer: ['#66c2a5', '#fc8d62', '#8da0cb', '#e78ac3', '#a6d854', '#ffd92f', '#e5c494', '#b3b3b3'],
  };
}

// console.log(Marker.colors.autoColorFromStates(['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'a']));
